### ISSUE TITLE
Event dialog remains on Event Details page

### ISSUE THREAD

**Issue by dalewl** [olinlibrary/abe-web#71]
The event pop-up hangs around after clicking on its link loads the Details page for the event. Firefox 54.0, Ubuntu Linux

Before clicking event ![Before clicking event](https://user-images.githubusercontent.com/11560346/28728429-3d1c2366-738e-11e7-8175-b416ba8d7db4.png)
After clicking event ![After clicking event](https://user-images.githubusercontent.com/11560346/28728428-3d1be608-738e-11e7-8017-977aae749b34.png)
Dialog remains on top of Details page it loaded ![Dialog remains on top of Details page it loaded](https://user-images.githubusercontent.com/11560346/28728431-3d486fde-738e-11e7-95cb-d84cf668d087.png)

**Comment by kylecombes** [comment]
This is a side effect of mixing React and jQuery. We will be replacing the current jQuery tooltip with a React implementation in the future, but a prerequisite for that is having a React calendar. I am developing one [here](https://github.com/kylecombes/ultra-responsive-calendar), since the other implementations out there aren't as flexible as we'd like. I hope to have it done by the end of August.

**Comment by kylecombes** [comment]
Ditching FullCalendar and jQuery, so no longer an issue.
